projConfig.toml for ringd_go

[meta]
    version = '0.1.0'

[project]
    name = 'ringd_go'  # distro name
    package = 'ringd_go'  # internal name
    main_lang = 'go'
    version = '0.0.1'
    version_date = '2017-05-18'
    author = 'Jim Dixon'
    author_email = 'jddixon@gmail.com'
    copyright = '2017
'
    description = 'full mesh of machines communicating using fieldz'
    dev_status = 'pre-alpha'
    license = 'mit'
    relpath = 'go/src/github.com/jddixon/ringd_go'
    state = 'shared'
    url = 'https://jddixon.github.io/ringd_go'

[go]
    cmds=[]
